experiment_dir: "/mnt/towbin.data/shared/spsalmon/20240823_SQUID_10x_yap1_del_dpy/"
analysis_dir_name: "analysis"

#########################################################################################################
################################# IMAGE ANALYSIS PIPELINE CONFIGURATION #################################
#########################################################################################################

building_blocks: ["segmentation", "segmentation", "straightening", "straightening", "straightening", "volume_computation", "volume_computation", "classification", "molt_detection"]

rerun_segmentation: [False]
rerun_straightening: [False]
rerun_volume_computation: [False]
rerun_classification: [False]
rerun_molt_detection: [False]
rerun_fluorescence_quantification: [False]
rerun_custom_script: [True]

# segmentation parameters
segmentation_column: ['raw']
segmentation_name_suffix: [null]
segmentation_method: ["edge_based", "edge_based"]
segmentation_channels: [[0], [1]]
augment_contrast: [False]

# edge-based segmentation parameters
pixelsize: [1.85]
sigma_canny: [1]

# deep learning segmentation parameters
model_path: ["/home/spsalmon/towbintools/towbintools/deep_learning/unet_confocal/epoch=105-step=16854.ckpt"]
tiler_config: [[[512, 512], [256, 256]]]
RGB: [True]
activation_layer: [null]
batch_size: [-1]

# ilastik segmentation parameters
ilastik_project_path: ["/home/igheor/towbintools_pipeline/models/pharynx_str_noCPR.ilp"]
ilastik_result_channel: [0]

# straightening parameters
straightening_source: [['analysis/ch2_seg', null], ['analysis/ch1_seg', null], ['raw', [0,1,2]]]
straightening_masks: ['analysis/ch2_seg']

# volume computation parameters
volume_computation_masks: ['analysis/ch2_seg_str', 'analysis/ch1_seg_str']

# classification parameters
classification_source: ['analysis/ch2_seg_str']
classifier: ["./models/worm_type_classifier.json"]

# molt detection parameters
molt_detection_volume: ['ch2_seg_str_volume']
molt_detection_worm_type: ['ch2_seg_str_worm_type']

# fluo quantification parameters
fluorescence_quantification_source: [['raw', 0]]
fluorescence_quantification_masks: ['analysis/ch1_seg']
fluorescence_quantification_aggregation: ['sum']
fluorescence_background_aggregation: ['median']

# custom parameters
custom_script_path: ["/home/spsalmon/test_custom_script.py"]
custom_script_name: ["test_custom_script"]
custom_script_return_type: ["subdir"]
custom_script_parameters: [["-i testinput"]]


# sbatch parameters
sbatch_memory: 128G
sbatch_time: 0-48:00:00
sbatch_cpus: 16
sbatch_gpus: 0

##########################################################################################################
################################## DATA ANALYSIS PIPELINE CONFIGURATION ##################################
##########################################################################################################

group_by: "point_range"
conditions:
  - rnai: "EV"
    strain:
      - wBT160
      - wBT415
    point_range:
      - [0, 27]
      - [59, 68]
  - rnai: "dpy-1"
    strain:  
      - wBT160
      - wBT415
    point_range:
      - [28, 58]
      - [69, 86]

# group_by: "pad"
# conditions:
#   - strain: wBT397
#     auxin_concentration_um: 1000
#     pad: pad1
#   - strain: wBT405
#     auxin_concentration_um: 1000
#     pad: pad2
