experiment_dir: "/mnt/towbin.data/shared/plenart/20232707_Ti2_wbt125_measuring_measurement_error_for_organ_size_paper/"
analysis_dir_name: "analysis_deep_learning"

building_blocks: ["segmentation", "segmentation", "straightening", "straightening", "volume_computation", "volume_computation", "classification"]

rerun_segmentation: [False]
rerun_straightening: [False]
rerun_volume_computation: [False]
rerun_classification: [False]
rerun_molt_detection: [False]
rerun_fluorescence_quantification: [False]
rerun_custom_script: [False]

# segmentation parameters
segmentation_column: ["raw"]
segmentation_name_suffix: [null, "edge_based"]
segmentation_method: ["edge_based"]
segmentation_channels: [[0], [1]]
augment_contrast: [False]

# edge-based segmentation parameters: pixel size hould be 0.65 for 10x, 0.325 for 20x
pixelsize: [0.65]
sigma_canny: [1]

# deep learning segmentation parameters
model_path: ["/home/spsalmon/towbintools/towbintools/deep_learning/unet_confocal/epoch=105-step=16854.ckpt"]
tiler_config: [[[512, 512], [256, 256]]]
RGB: [True]
activation_layer: [null]
batch_size: [-1]

# ilastik segmentation parameters
ilastik_project_path: ["/home/igheor/towbintools_pipeline/models/pharynx_str_noCPR.ilp"]
ilastik_result_channel: [0]

# straightening parameters
straightening_source: [['analysis_deep_learning/ch1_seg', null], ['analysis_deep_learning/ch2_seg_edge_based', null]]
straightening_masks: ['analysis_deep_learning/ch2_seg_edge_based']

# volume computation parameters
volume_computation_masks: ['analysis_deep_learning/ch1_seg_str', 'analysis_deep_learning/ch2_seg_edge_based_str']

# classification parameters
classification_source: ['analysis_deep_learning/ch2_seg_edge_based_str']
classifier: ["./models/worm_type_classifier.json"]

# molt detection parameters
molt_detection_volume: ['ch1_seg_str_volume']
molt_detection_worm_type: ['ch1_seg_str_worm_type']

# fluo quantification parameters
fluorescence_quantification_source: [['raw', 0]]
fluorescence_quantification_masks: ['analysis/ch1_seg']
fluorescence_quantification_aggregation: ['sum']
fluorescence_background_aggregation: ['median']

# custom parameters
custom_script_path : ["//mnt/towbin.data/shared/unoesberger/Experiments/wBT413_wBT148_wBT123_N2_starvation/20240517/analysis_scripts/extract_best_plane.sh"]
custom_script_name : ["extract_best_plane"]
custom_script_return_type : ["null"]
custom_script_parameters : [""]



# sbatch parameters
sbatch_memory: 128G
sbatch_time: 0-48:00:00
sbatch_cpus: 32
sbatch_gpus: 0
