image_directories: ["/mnt/towbin.data/shared/spsalmon/towbinlab_segmentation_database/body/images"]
mask_directories: ["/mnt/towbin.data/shared/spsalmon/towbinlab_segmentation_database/body/binarized_and_cleaned_masks/"]

# training_filemap: '/mnt/external.data/TowbinLab/plenart/20221020_Ti2_10x_green_bacteria_wbt150_small_chambers_good/analysis/report/training_filemap.csv'

save_dir: '/mnt/towbin.data/shared/spsalmon/towbinlab_segmentation_database/models/body/'
model_name: 'SAMannotations_singleclass_UnetPlusPlus_efficientnet-b4_image-micronet_FocalTversky'

pretrained: True

continue_training_from_checkpoint: null

n_classes: 1
channels_to_segment: [0]

architecture: 'UnetPlusPlus'
pretrained_encoder: 'efficientnet-b4'
pretrained_weights: 'image-micronet'

deep_supervision: False

learning_rate: 1.0e-4
normalization_parameters: {'type': 'percentile', 'lo': 1, 'hi': 99, 'axis': [-2, -1]}

train_on_tiles: True
tiler_config: {'tile_size':[1024, 1024], 'tile_step':[256, 256]}

loss: 'FocalTversky'
value_to_ignore: -1

max_epochs: 1000
batch_size: 24
accumulate_grad_batches: 2
num_workers: 16

save_best_k_models: 1
train_val_split_ratio: 0.25
train_test_split_ratio: 0.1
