image_directories: ["/mnt/towbin.data/shared/spsalmon/screen_analysis_segmentation_database/adult_pharynxes/good_images"]
mask_directories: ["/mnt/towbin.data/shared/spsalmon/screen_analysis_segmentation_database/adult_pharynxes/binarized_and_cleaned_masks"]

# training_filemap: '/mnt/external.data/TowbinLab/plenart/20221020_Ti2_10x_green_bacteria_wbt150_small_chambers_good/analysis/report/training_filemap.csv'

# training_dataframes: ['/mnt/towbin.data/shared/spsalmon/towbinlab_segmentation_database/initial_annotations/pharynx/datasets/training_dataframe.csv',
#                       '/mnt/towbin.data/shared/spsalmon/towbinlab_segmentation_database/squid_fine_tuning/pharynx/datasets/training_dataframe.csv']

# validation_dataframes: ['/mnt/towbin.data/shared/spsalmon/towbinlab_segmentation_database/initial_annotations/pharynx/datasets/validation_dataframe.csv',
#                       '/mnt/towbin.data/shared/spsalmon/towbinlab_segmentation_database/squid_fine_tuning/pharynx/datasets/validation_dataframe.csv']

# test_dataframes: ['/mnt/towbin.data/shared/spsalmon/towbinlab_segmentation_database/initial_annotations/pharynx/datasets/test_dataframe.csv',
#                       '/mnt/towbin.data/shared/spsalmon/towbinlab_segmentation_database/squid_fine_tuning/pharynx/datasets/test_dataframe.csv']

save_dir: '/mnt/towbin.data/shared/spsalmon/screen_analysis_segmentation_database/models'
model_name: 'aldult_pharynxes_screen_model'

pretrained: True

continue_training_from_checkpoint: null

n_classes: 2
channels_to_segment: [0]

architecture: 'UPerNet'
pretrained_encoder: 'mit_b3'
pretrained_weights: 'imagenet'

deep_supervision: False

learning_rate: 1.0e-4
normalization_parameters: {'type': 'percentile', 'lo': 1, 'hi': 99, 'axis': [-2, -1]}

train_on_tiles: True
tiler_config: {'tile_size':[1024, 1024], 'tile_step':[256, 256]}

loss: 'MultiClassFocalLoss'
value_to_ignore: -1

max_epochs: 500
batch_size: 24
accumulate_grad_batches: 2
num_workers: 16

save_best_k_models: 1
train_val_split_ratio: 0.20
train_test_split_ratio: 0.1
