training_dataframes:
  - '/mnt/towbin.data/shared/spsalmon/towbinlab_segmentation_database/towbintools_paper/pharynx/training_dataframe.csv'

validation_dataframes:
  - '/mnt/towbin.data/shared/spsalmon/towbinlab_segmentation_database/towbintools_paper/pharynx/validation_dataframe.csv'

test_dataframes:
  - '/mnt/towbin.data/shared/spsalmon/towbinlab_segmentation_database/towbintools_paper/pharynx/test_dataframe.csv'

save_dir: '/mnt/towbin.data/shared/spsalmon/towbinlab_segmentation_database/models/paper/pharynx/'
model_name: 'towbintools_medium'

pretrained: True

continue_training_from_checkpoint: '/mnt/towbin.data/shared/spsalmon/towbinlab_segmentation_database/models/paper/body/towbintools_medium/best_light.ckpt'

n_classes: 1
channels_to_segment: [0]

architecture: 'UnetPlusPlus'
pretrained_encoder: 'efficientnet-b5'
pretrained_weights: 'imagenet'

deep_supervision: False

learning_rate: 1.0e-4
normalization_parameters: {'type': 'percentile', 'lo': 1, 'hi': 99, 'axis': [-2, -1]}

train_on_tiles: True
tiler_config: {'tile_size':[1024, 1024], 'tile_step':[256, 256]}

loss: 'FocalTversky'
value_to_ignore: -1

max_epochs: 500
batch_size: 8
accumulate_grad_batches: 3
num_workers: 24
deterministic: True # slower training but ensures reproducibility

save_best_k_models: 1
train_val_split_ratio: 0.20
train_test_split_ratio: 0.1
