name: towbintools
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pyyaml
  - seaborn
  - statsmodels
  - plotly
  - ipykernel
  - polars
  - pyarrow
  - bottleneck
  - numcodecs<0.16
  - pip

  # development dependencies
  - pytest
  - black
  - isort
  - conda-lock
  - pre-commit
  - mypy
  - flake8
  - tox

  - pip:
    - bioio
    - bioio-ome-tiff
    - bioio-ome-zarr
    - crc32c # missing dependency for bioio-ome-tiff
    - microfilm
    - towbintools
    - shiny
    - shinywidgets
    - statannotations
    - tensorboard
